/**
 * Deterministic, fake, clearly-fictional offer/source data used ONLY by
 * the Playwright-only local PostgREST-shaped test server (`server.mjs`).
 * Plain JavaScript, not TypeScript, and lives entirely under `e2e/` —
 * never imported by, or reachable from, anything under `src/` (M3
 * review: the previous in-process fake Supabase client lived under
 * `src/lib/offers/test-data/` and was statically imported by
 * `src/lib/db/public-client.ts`, so a clean production build shipped
 * this fictional data and the `PFE_E2E_TEST_DATA` flag inside
 * `.next/server`). See `scripts/scan-production-bundle.mjs` for the CI
 * regression check that a real build never contains any of this again.
 *
 * Shaped to exercise the full M3 experience: 14 active offers across
 * both countries, all six specialties, several technologies, every work
 * mode, mixed PFE/non-PFE, mixed known/unknown city and publication
 * date, plus 1 inactive offer that must never appear. 14 active rows
 * (> the default page size of 12) guarantees a "load more" page exists.
 */

const DAY_MS = 24 * 60 * 60 * 1000
const daysAgo = (days) => new Date(Date.now() - days * DAY_MS).toISOString()

function offer(overrides) {
  return {
    source_key: 'smartrecruiters-inetum',
    source_url: `https://jobs.smartrecruiters.com/Inetum2/${overrides.external_id}`,
    apply_url: `https://jobs.smartrecruiters.com/Inetum2/${overrides.external_id}/apply`,
    canonical_url_hash: `test-hash-${overrides.external_id}`,
    description_text: 'Description de test générée pour les vérifications Playwright de bout en bout.',
    country: 'MA',
    city: 'Casablanca',
    region: null,
    work_mode: 'onsite',
    internship_type: 'internship',
    is_pfe: false,
    specialties: [],
    technologies: [],
    language: 'fr',
    published_at: daysAgo(1),
    first_seen_at: daysAgo(1),
    last_seen_at: daysAgo(0),
    inactive_at: null,
    status: 'active',
    created_at: daysAgo(1),
    updated_at: daysAgo(0),
    ...overrides,
  }
}

export const TEST_OFFER_ROWS = [
  offer({
    id: 'aaaaaaaa-0000-4000-8000-000000000001',
    external_id: 'e2e-1',
    title: 'Stage PFE Développeur Full Stack',
    company: 'Atlas Software',
    city: 'Casablanca',
    country: 'MA',
    work_mode: 'remote',
    is_pfe: true,
    specialties: ['software-web-mobile'],
    technologies: ['React', 'Node.js'],
    language: 'fr',
    published_at: daysAgo(1),
    last_seen_at: daysAgo(0),
  }),
  offer({
    id: 'aaaaaaaa-0000-4000-8000-000000000002',
    external_id: 'e2e-2',
    title: 'Stage Data Scientist',
    company: 'Rivage Analytics',
    city: 'Rabat',
    country: 'MA',
    work_mode: 'hybrid',
    specialties: ['data-ai'],
    technologies: ['Python', 'TensorFlow'],
    language: 'fr',
    published_at: daysAgo(2),
    last_seen_at: daysAgo(0),
  }),
  offer({
    id: 'aaaaaaaa-0000-4000-8000-000000000003',
    external_id: 'e2e-3',
    title: 'Stage Cybersécurité',
    company: 'Cardinal Security',
    city: 'Paris',
    country: 'FR',
    work_mode: 'onsite',
    specialties: ['cybersecurity'],
    technologies: ['Linux'],
    language: 'fr',
    published_at: daysAgo(3),
    last_seen_at: daysAgo(1),
  }),
  offer({
    id: 'aaaaaaaa-0000-4000-8000-000000000004',
    external_id: 'e2e-4',
    title: 'Stage Cloud DevOps',
    company: 'Nimbus Cloud',
    city: 'Lyon',
    country: 'FR',
    work_mode: 'hybrid',
    is_pfe: true,
    specialties: ['cloud-devops'],
    technologies: ['Docker', 'Kubernetes', 'Terraform'],
    language: 'fr',
    published_at: daysAgo(4),
    last_seen_at: daysAgo(0),
  }),
  offer({
    id: 'aaaaaaaa-0000-4000-8000-000000000005',
    external_id: 'e2e-5',
    title: 'Stage Administrateur Systèmes et Réseaux',
    company: 'Meridian Networks',
    city: 'Marrakech',
    country: 'MA',
    work_mode: 'onsite',
    specialties: ['systems-networks'],
    technologies: ['Linux'],
    language: 'fr',
    published_at: daysAgo(5),
    last_seen_at: daysAgo(1),
  }),
  offer({
    id: 'aaaaaaaa-0000-4000-8000-000000000006',
    external_id: 'e2e-6',
    title: 'Stage QA / Test Automation',
    company: 'Verity QA',
    city: 'Casablanca',
    country: 'MA',
    work_mode: 'unknown',
    specialties: ['qa-testing'],
    technologies: ['Git'],
    language: 'fr',
    published_at: daysAgo(6),
    last_seen_at: daysAgo(2),
  }),
  offer({
    id: 'aaaaaaaa-0000-4000-8000-000000000007',
    external_id: 'e2e-7',
    title: 'Final-Year Internship Backend Engineer',
    company: 'Solstice Systems',
    city: null,
    region: null,
    country: 'FR',
    work_mode: 'remote',
    is_pfe: true,
    specialties: ['software-web-mobile'],
    technologies: ['Java', 'Spring'],
    language: 'en',
    published_at: null,
    last_seen_at: daysAgo(0),
  }),
  offer({
    id: 'aaaaaaaa-0000-4000-8000-000000000008',
    external_id: 'e2e-8',
    title: 'Machine Learning Internship',
    company: 'Vector Labs',
    city: 'Tangier',
    country: 'MA',
    work_mode: 'hybrid',
    specialties: ['data-ai'],
    technologies: ['Python', 'PyTorch'],
    language: 'en',
    published_at: daysAgo(7),
    last_seen_at: daysAgo(3),
  }),
  offer({
    id: 'aaaaaaaa-0000-4000-8000-000000000009',
    external_id: 'e2e-9',
    title: 'Stage Développeur Mobile',
    company: 'Atlas Software',
    city: 'Casablanca',
    country: 'MA',
    work_mode: 'onsite',
    specialties: ['software-web-mobile'],
    technologies: ['React'],
    language: 'fr',
    published_at: daysAgo(8),
    last_seen_at: daysAgo(4),
  }),
  offer({
    id: 'aaaaaaaa-0000-4000-8000-00000000000a',
    external_id: 'e2e-10',
    title: 'Stage Ingénieur Cloud',
    company: 'Nimbus Cloud',
    city: 'Bordeaux',
    country: 'FR',
    work_mode: 'remote',
    specialties: ['cloud-devops'],
    technologies: ['AWS'],
    language: 'fr',
    published_at: daysAgo(9),
    last_seen_at: daysAgo(5),
  }),
  offer({
    id: 'aaaaaaaa-0000-4000-8000-00000000000b',
    external_id: 'e2e-11',
    title: 'Stage Pentest & Sécurité Offensive',
    company: 'Cardinal Security',
    city: 'Rabat',
    country: 'MA',
    work_mode: 'onsite',
    is_pfe: true,
    specialties: ['cybersecurity'],
    technologies: ['Linux'],
    language: 'fr',
    published_at: daysAgo(10),
    last_seen_at: daysAgo(6),
  }),
  offer({
    id: 'aaaaaaaa-0000-4000-8000-00000000000c',
    external_id: 'e2e-12',
    title: 'Stage Réseaux & Télécoms',
    company: 'Meridian Networks',
    city: 'Fes',
    country: 'MA',
    work_mode: 'unknown',
    specialties: ['systems-networks'],
    technologies: [],
    language: 'fr',
    published_at: daysAgo(11),
    last_seen_at: daysAgo(7),
  }),
  offer({
    id: 'aaaaaaaa-0000-4000-8000-00000000000d',
    external_id: 'e2e-13',
    title: 'QA Automation Internship',
    company: 'Verity QA',
    city: 'Marseille',
    country: 'FR',
    work_mode: 'hybrid',
    specialties: ['qa-testing'],
    technologies: ['Git'],
    language: 'en',
    published_at: daysAgo(12),
    last_seen_at: daysAgo(8),
  }),
  offer({
    id: 'aaaaaaaa-0000-4000-8000-00000000000e',
    external_id: 'e2e-14',
    title: 'Stage Développeur Web Junior',
    company: 'Atlas Software',
    city: 'Casablanca',
    country: 'MA',
    work_mode: 'onsite',
    specialties: ['software-web-mobile'],
    technologies: ['JavaScript'],
    language: 'fr',
    published_at: daysAgo(13),
    last_seen_at: daysAgo(9),
  }),
  // Inactive — must never appear in search results or resolve at
  // /offers/{id}.
  offer({
    id: 'aaaaaaaa-0000-4000-8000-00000000000f',
    external_id: 'e2e-inactive',
    title: 'Stage Archivé',
    company: 'Legacy Corp',
    city: 'Casablanca',
    country: 'MA',
    status: 'inactive',
    inactive_at: daysAgo(40),
    published_at: daysAgo(50),
    last_seen_at: daysAgo(40),
  }),
]

/** Mixed fresh/stale/null so the freshness banner is genuinely
 * exercisable end-to-end (M3 review finding 6). */
export const TEST_SOURCE_ROWS = [
  { key: 'smartrecruiters-inetum', enabled: true, last_success_at: daysAgo(0) },
  { key: 'smartrecruiters-devoteam', enabled: true, last_success_at: daysAgo(3) },
  { key: 'smartrecruiters-mazars', enabled: true, last_success_at: null },
]
